"""empty message

Revision ID: df1cb7a5a659
Revises: 73d4bf703188
Create Date: 2020-07-14 21:07:50.113797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1cb7a5a659'
down_revision = '73d4bf703188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'shows', ['artist_id', 'start_time'])
    op.create_unique_constraint(None, 'shows', ['artist_id', 'venue_id', 'start_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='unique')
    op.drop_constraint(None, 'shows', type_='unique')
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###
